name: custom_painter_playground
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.3
  freezed_annotation: ^3.1.0
  go_router: ^16.3.0
  riverpod_annotation: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.7.1
  custom_lint: ^0.8.0
  flutter_lints: ^5.0.0
  freezed: ^3.2.3
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true

  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-VariableFont_wght.ttf
